[input]
base_directory = "D:/SOFTWARE_PRUDUCT/GithubDesktop/repository/rgchuan13.github.io/output"
html_selector = "main"

[[input.files]]
path = "pages/about.html"
url = "/pages/about.html"
title = "About"

[[input.files]]
path = "pages/events.html"
url = "/pages/events.html"
title = "Events"

[[input.files]]
path = "latch_up_io_esd_learn.html"
url = "/latch_up_io_esd_learn.html"
title = "Layout Guidelines for Latch-up and IO ESD"

[[input.files]]
path = "cadence_learn.html"
url = "/cadence_learn.html"
title = "cadence学习笔记"

[[input.files]]
path = "virtuoso_learn.html"
url = "/virtuoso_learn.html"
title = "virtuoso学习笔记"

[[input.files]]
path = "nfc_method.html"
url = "/nfc_method.html"
title = "NFC 基础"

[[input.files]]
path = "ebook_store.html"
url = "/ebook_store.html"
title = "电子藏书目录"

[[input.files]]
path = "commonly_used_tools_memo.html"
url = "/commonly_used_tools_memo.html"
title = "小工具操作备忘"