[input]
base_directory = "D:/SOFTWARE_PRUDUCT/GithubDesktop/repository/rgchuan13.github.io/output"
html_selector = "title"

[[input.files]]
path = "pages/about.html"
url = "/pages/about.html"
title = "About"

[[input.files]]
path = "pages/events.html"
url = "/pages/events.html"
title = "events"

[[input.files]]
path = "commonly_used_tools_memo.html"
url = "/commonly_used_tools_memo.html"
title = "commonly used tools memo"

[[input.files]]
path = "graduation_project_memo.html"
url = "/graduation_project_memo.html"
title = "graduation project memo"