[input]
base_directory = "D:/SOFTWARE_PRUDUCT/GithubDesktop/repository/rgchuan13.github.io/output"
html_selector = "main"

[[input.files]]
path = "pages/about.html"
url = "/pages/about.html"
title = "About"

[[input.files]]
path = "pages/events.html"
url = "/pages/events.html"
title = "Events"

[[input.files]]
path = "commonly_used_tools_memo.html"
url = "/commonly_used_tools_memo.html"
title = "小工具操作备忘"

[[input.files]]
path = "graduation_project_memo.html"
url = "/graduation_project_memo.html"
title = "基于 CycloneV 的 SoC 数字系统设计（毕设备忘）"